# To use:
#   $ conda env create -f environment.yml
#   $ conda activate aq_by_entropy
name: aq_by_entropy
dependencies:
  - python=3.9
  - pip
  - ipykernel
  - pip:
    - pandas
    - numpy
    - scipy
    - requests
    - ipywidgets
    - scikit-learn
    - matplotlib
    - seaborn
